name: Lint

on:
  push:
  pull_request:

permissions:
  contents: write
  packages: read
  statuses: write

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Super-Linter with AutoFix
        uses: super-linter/super-linter@v7.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_AND_AUTOFIX: true

      - name: Commit and push fixes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "chore: auto-fix lint issues [skip ci]" || echo "No changes"
          git push
